# Generated by Django 5.2.14 on 2026-07-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_doctor_specialty_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='شماره تلفن مطب / کلینیک'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='collaboration_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع همکاری'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_last_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین تمدید پروانه'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_system_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='شماره نظام پزشکی'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='شماره تلفن همراه'),
        ),
    ]
