# Generated by Django 5.2.14 on 2026-06-03 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surgeries', '0007_center_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterCommissionIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ درآمد')),
                ('status', models.CharField(choices=[('CONFIRMED', 'تأیید شده'), ('CANCELLED', 'لغو شده')], default='CONFIRMED', max_length=10, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('income_date', models.DateTimeField(verbose_name='تاریخ درآمد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center_commission_income', to='surgeries.surgeryhistory', verbose_name='عمل جراحی')),
            ],
            options={
                'verbose_name': 'درآمد کمیسیون مرکز',
                'verbose_name_plural': 'درآمدهای کمیسیون مرکز',
                'ordering': ['-income_date', '-created_at'],
                'indexes': [models.Index(fields=['surgery'], name='idx_cci_surgery'), models.Index(fields=['status'], name='idx_cci_status'), models.Index(fields=['income_date'], name='idx_cci_income_date')],
            },
        ),
    ]
