# Generated by Django 5.2.14 on 2026-06-04 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0001_center_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('category_type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], max_length=10, verbose_name='نوع دسته\u200cبندی')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مالی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مالی',
                'ordering': ['category_type', 'name'],
                'indexes': [models.Index(fields=['category_type'], name='idx_fc_category_type'), models.Index(fields=['is_active'], name='idx_fc_is_active')],
                'unique_together': {('name', 'category_type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], max_length=10, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ باید بزرگ\u200cتر از صفر باشد.', max_digits=14, verbose_name='مبلغ')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تراکنش')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('partial', 'پرداخت ناقص'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=10, verbose_name='وضعیت پرداخت')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه شیء مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financecategory', verbose_name='دسته\u200cبندی')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع شیء مرتبط')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش\u200cهای مالی',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_type'], name='idx_tx_type'), models.Index(fields=['transaction_date'], name='idx_tx_date'), models.Index(fields=['payment_status'], name='idx_tx_payment_status'), models.Index(fields=['category'], name='idx_tx_category'), models.Index(fields=['content_type', 'object_id'], name='idx_tx_gfk')],
            },
        ),
    ]
