# Generated by Django 5.2.14 on 2026-06-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_seed_job_positions'),
        ('inventory', '0008_purchase_purchaseitem_purchase_idx_purchase_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نرخ پایه برای محاسبه حقوق ساعتی. مقدار در رکورد ماهانه snapshot می\u200cشود.', max_digits=14, null=True, verbose_name='نرخ هر ساعت (تومان)'),
        ),
        migrations.CreateModel(
            name='EmployeePurchaseCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ کمیسیون (تومان)')),
                ('commission_date', models.DateField(verbose_name='تاریخ کمیسیون')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات / دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_commissions', to='employees.employee', verbose_name='کارمند')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_commissions', to='inventory.purchase', verbose_name='فاکتور خرید')),
            ],
            options={
                'verbose_name': 'کمیسیون خرید',
                'verbose_name_plural': 'کمیسیون\u200cهای خرید',
                'ordering': ['-commission_date'],
                'indexes': [models.Index(fields=['employee'], name='idx_epc_employee'), models.Index(fields=['commission_date'], name='idx_epc_date')],
            },
        ),
    ]
