# Generated by Django 5.2.14 on 2026-07-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_hourly_rate_purchase_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='بخشی از سامانه قدیمی حقوق ساعتی — فقط برای سازگاری با رکوردهای قبلی («رکوردهای ساعات کاری ماهانه») نگه داشته شده و برای کارمندان جدید استفاده نمی\u200cشود.', max_digits=14, null=True, verbose_name='نرخ هر ساعت (قدیمی / بایگانی)'),
        ),
    ]
