# Generated by Django 5.2.14 on 2026-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_employee_credential_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', help_text='شماره تماس در مواقع اضطراری (مثلاً خانواده).', max_length=20, verbose_name='تلفن اضطراری'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, help_text='اختیاری — در صورت تکمیل، باید منحصربه\u200cفرد باشد.', max_length=20, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='تلفن شخصی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id__isnull', False), models.Q(('national_id', ''), _negated=True)), fields=('national_id',), name='unique_employee_national_id_when_set', violation_error_message='کد ملی باید یکتا باشد.'),
        ),
    ]
