# Generated by Django 5.2.14 on 2026-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('specialty', models.CharField(max_length=200, verbose_name='تخصص')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس')),
                ('center_commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد کمیسیون مرکز')),
                ('cooperation_status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('pending', 'در انتظار')], default='active', max_length=10, verbose_name='وضعیت همکاری')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس دکتر',
                'verbose_name_plural': 'اطلاعات تماس دکترها',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_dc_is_active'), models.Index(fields=['cooperation_status'], name='idx_dc_coop_status'), models.Index(fields=['phone_number'], name='idx_dc_phone')],
            },
        ),
    ]
