# Generated by Django 5.2.14 on 2026-08-20 16:00

import common.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='عنوان تخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تخصص پزشک',
                'verbose_name_plural': 'تخصص\u200cهای پزشکان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(blank=True, default='', max_length=20, verbose_name='کد ملی')),
                ('medical_system_number', models.CharField(blank=True, default='', max_length=30, verbose_name='شماره نظام پزشکی')),
                ('collaboration_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع همکاری')),
                ('license_last_renewal_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین تمدید پروانه')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تلفن همراه')),
                ('clinic_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='شماره تلفن مطب / کلینیک')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس')),
                ('medical_certificate_image', models.ImageField(blank=True, upload_to=common.uploads.doctor_medical_certificate_upload_path, validators=[common.uploads.validate_image_upload], verbose_name='مدرک پزشکی')),
                ('national_card_image', models.ImageField(blank=True, upload_to=common.uploads.doctor_national_card_upload_path, validators=[common.uploads.validate_image_upload], verbose_name='کارت ملی')),
                ('center_commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد کمیسیون مرکز')),
                ('rate_per_surgery', models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ ثابت دستمزد پزشک به ازای هر عمل. می\u200cتواند برای هر پزشک متفاوت باشد.', max_digits=14, null=True, verbose_name='نرخ هر عمل (تومان)')),
                ('cooperation_status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('pending', 'در انتظار')], default='active', max_length=10, verbose_name='وضعیت همکاری')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='contacts.doctorspecialty', verbose_name='تخصص')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس دکتر',
                'verbose_name_plural': 'اطلاعات تماس دکترها',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSurgeryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='نرخ هر عمل (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_rates', to='contacts.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'نرخ پزشک به ازای نوع عمل',
                'verbose_name_plural': 'نرخ\u200cهای پزشک به تفکیک نوع عمل',
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active'], name='idx_dc_is_active'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['cooperation_status'], name='idx_dc_coop_status'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['phone_number'], name='idx_dc_phone'),
        ),
    ]
