# Generated by Django 5.2.14 on 2026-08-20 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('surgeries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsurgeryrate',
            options={'ordering': ['doctor__full_name', 'surgery_type__name'], 'verbose_name': 'نرخ پزشک به ازای نوع عمل', 'verbose_name_plural': 'نرخ\u200cهای پزشک به تفکیک نوع عمل'},
        ),
        migrations.AddField(
            model_name='doctorsurgeryrate',
            name='surgery_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_rates', to='surgeries.surgerytype', verbose_name='نوع عمل'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='doctorsurgeryrate',
            unique_together={('doctor', 'surgery_type')},
        ),
    ]
