# Generated by Django 5.2.14 on 2026-07-08 15:10

import common.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_doctor_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='medical_certificate_image',
            field=models.ImageField(blank=True, upload_to=common.uploads.doctor_medical_certificate_upload_path, validators=[common.uploads.validate_image_upload], verbose_name='مدرک پزشکی'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='national_card_image',
            field=models.ImageField(blank=True, upload_to=common.uploads.doctor_national_card_upload_path, validators=[common.uploads.validate_image_upload], verbose_name='کارت ملی'),
        ),
    ]
