# Generated by Django 5.2.14 on 2026-07-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_doctor_first_name_doctor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='contacts.doctorspecialty', verbose_name='تخصص'),
        ),
    ]
