# Generated by Django 5.2.14 on 2026-06-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financecategory_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
            ],
            options={
                'verbose_name': 'دسته\u200cبندی هزینه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای هزینه',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.financecategory',),
        ),
    ]
