# Generated by Django 5.2.14 on 2026-07-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_doctorsurgeryrate'),
        ('finance', '0007_seed_monthly_expense_categories'),
        ('surgeries', '0014_alter_surgerytype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFeeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ حق\u200cالزحمه')),
                ('status', models.CharField(choices=[('CONFIRMED', 'تأیید شده'), ('CANCELLED', 'لغو شده')], default='CONFIRMED', max_length=10, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('fee_date', models.DateTimeField(verbose_name='تاریخ محاسبه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_expenses', to='contacts.doctor', verbose_name='پزشک')),
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_fee_expense', to='surgeries.surgeryhistory', verbose_name='عمل جراحی')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_fee_expenses', to='surgeries.surgerytype', verbose_name='نوع عمل')),
            ],
            options={
                'verbose_name': 'حق\u200cالزحمه پزشک',
                'verbose_name_plural': 'حق\u200cالزحمه\u200cهای پزشکان',
                'ordering': ['-fee_date', '-created_at'],
                'indexes': [models.Index(fields=['surgery'], name='idx_dfe_surgery'), models.Index(fields=['doctor'], name='idx_dfe_doctor'), models.Index(fields=['status'], name='idx_dfe_status')],
            },
        ),
    ]
