# Generated by Django 5.2.14 on 2026-08-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_doctorfeeexpense'),
        ('surgeries', '0021_alter_patient_case_code_alter_patient_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ماه')),
                ('center_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد کمیسیون مرکز جراحی')),
                ('university_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد کمیسیون دانشگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'کمیسیون ماهانه',
                'verbose_name_plural': 'کمیسیون ماهانه',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SurgeryTypeRateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ماه')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='نرخ پایه (تومان)')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_schedules', to='surgeries.surgerytype', verbose_name='نوع عمل')),
            ],
            options={
                'verbose_name': 'نرخ عمل',
                'verbose_name_plural': 'نرخ عمل',
                'ordering': ['-year', '-month', 'surgery_type__name'],
                'indexes': [models.Index(fields=['surgery_type', 'year', 'month'], name='idx_strs_type_year_month')],
                'unique_together': {('surgery_type', 'year', 'month')},
            },
        ),
    ]
