# Generated by Django 5.2.14 on 2026-08-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_doctorfeeexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='financecategory',
            name='slug',
            field=models.SlugField(default='temp', help_text='کد یکتا برای استفاده در محاسبات سیستمی (مثلاً medicine-cost)', max_length=100, verbose_name='شناسه یکتا (Slug)'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='financecategory',
            index=models.Index(fields=['slug'], name='idx_fc_slug'),
        ),
    ]
