# Generated by Django 5.2.14 on 2026-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_financecategory_slug_financecategory_idx_fc_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financecategory',
            name='slug',
            field=models.SlugField(help_text='کد یکتا برای استفاده در محاسبات سیستمی (مثلاً medicine-cost)', max_length=100, unique=True, verbose_name='شناسه یکتا (Slug)'),
        ),
    ]
