# Generated by Django 5.2.14 on 2026-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_financecategory_slug_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnesthesiaRateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ماه')),
                ('rate_per_anesthesia', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='نرخ ثابت هر بیهوشی (تومان)')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'نرخ ثابت بیهوشی',
                'verbose_name_plural': 'نرخ ثابت بیهوشی',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
