"""Surgery → inventory flow unit tests (CLI-61).

Covers gaps not present in the existing test_surgery_history.py:
- movement description contains patient full name
- movement description contains surgery type name
- multiple SurgeryUsedItems deplete multiple products correctly
- source_type is SURGERY_CONSUMPTION (explicit regression guard)

The following are already tested in test_surgery_history.py and are
NOT duplicated here:
- stock decrease by consumed quantity
- OUT movement created
- reference_id contains surgery.pk
- insufficient stock raises ValidationError
- atomic rollback (item not saved if movement fails)
- movement_date matches surgery.surgery_date
- zero/negative quantity rejected
- PATCH product/quantity fields are read-only on update
"""

import datetime
from decimal import Decimal

from django.contrib.auth.models import User
from django.test import TestCase
from rest_framework.test import APITestCase

from inventory.models import (
    MovementType,
    Product,
    ProductType,
    SourceType,
    StockMovement,
)
from surgeries.models import (
    Patient,
    PaymentStatus,
    SurgeryHistory,
    SurgeryStatus,
    SurgeryType,
    SurgeryUsedItem,
)
from surgeries.services import SurgeryInventoryService


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ctr = 0


def _surgery_type(name=None):
    global _ctr
    _ctr += 1
    return SurgeryType.objects.create(
        name=name or f"نوع جراحی {_ctr}",
        code=f"st_{_ctr}",
        base_rate=Decimal("500000"),
    )


def _patient(name=None):
    global _ctr
    _ctr += 1
    return Patient.objects.create(
        full_name=name or f"بیمار {_ctr}",
        case_code=f"STIN-{_ctr:05d}",
        phone_number="09100000000",
    )


def _surgery(patient, surgery_type, amount=Decimal("5000000")):
    return SurgeryHistory.objects.create(
        patient=patient,
        surgery_type=surgery_type,
        amount=amount,
        surgery_date=datetime.datetime(2025, 6, 1, 10, 0,
                                       tzinfo=datetime.timezone.utc),
        status=SurgeryStatus.COMPLETED,
        payment_status=PaymentStatus.PAID,
    )


def _product(stock=Decimal("100"), **kwargs):
    global _ctr
    _ctr += 1
    defaults = {
        "name":          f"دارو {_ctr}",
        "internal_code": f"SIN-{_ctr:04d}",
        "product_type":  ProductType.MEDICINE,
        "unit":          "عدد",
    }
    defaults.update(kwargs)
    p = Product.objects.create(**defaults)
    if stock:
        p._apply_stock_delta(stock)
        p.refresh_from_db()
    return p


def _used_item(surgery, product, quantity=Decimal("10")):
    item = SurgeryUsedItem.objects.create(
        surgery=surgery, product=product, quantity=quantity,
    )
    SurgeryInventoryService.consume_product(item)
    return item


# ---------------------------------------------------------------------------
# Movement description content
# ---------------------------------------------------------------------------

class SurgeryMovementDescriptionTest(TestCase):
    """The movement description generated by SurgeryInventoryService
    must include the patient name and surgery type name."""

    def setUp(self):
        self.surgery_type = _surgery_type(name="بینی‌زیبایی")
        self.patient      = _patient(name="زهرا موسوی")
        self.surgery      = _surgery(self.patient, self.surgery_type)
        self.product      = _product()

    def test_description_contains_patient_full_name(self):
        item = _used_item(self.surgery, self.product)
        mv = StockMovement.objects.filter(product=self.product).first()
        self.assertIn("زهرا موسوی", mv.description)

    def test_description_contains_surgery_type_name(self):
        item = _used_item(self.surgery, self.product)
        mv = StockMovement.objects.filter(product=self.product).first()
        self.assertIn("بینی‌زیبایی", mv.description)

    def test_source_type_is_surgery_consumption(self):
        item = _used_item(self.surgery, self.product)
        mv = StockMovement.objects.filter(product=self.product).first()
        self.assertEqual(mv.source_type, SourceType.SURGERY_CONSUMPTION)

    def test_movement_type_is_out(self):
        item = _used_item(self.surgery, self.product)
        mv = StockMovement.objects.filter(product=self.product).first()
        self.assertEqual(mv.movement_type, MovementType.OUT)


# ---------------------------------------------------------------------------
# Multiple products consumed in one surgery
# ---------------------------------------------------------------------------

class SurgeryMultipleProductsTest(TestCase):
    """Consuming multiple distinct products in one surgery must decrease
    each product's stock independently and create one OUT movement per product."""

    def setUp(self):
        self.surgery_type = _surgery_type()
        self.patient      = _patient()
        self.surgery      = _surgery(self.patient, self.surgery_type)
        self.p1 = _product(stock=Decimal("50"))
        self.p2 = _product(stock=Decimal("80"))
        self.p3 = _product(stock=Decimal("30"))

    def test_three_products_each_decreased_correctly(self):
        _used_item(self.surgery, self.p1, quantity=Decimal("10"))
        _used_item(self.surgery, self.p2, quantity=Decimal("20"))
        _used_item(self.surgery, self.p3, quantity=Decimal("5"))

        self.p1.refresh_from_db()
        self.p2.refresh_from_db()
        self.p3.refresh_from_db()

        self.assertEqual(self.p1.current_stock, Decimal("40"))
        self.assertEqual(self.p2.current_stock, Decimal("60"))
        self.assertEqual(self.p3.current_stock, Decimal("25"))

    def test_three_products_three_out_movements(self):
        _used_item(self.surgery, self.p1, quantity=Decimal("10"))
        _used_item(self.surgery, self.p2, quantity=Decimal("20"))
        _used_item(self.surgery, self.p3, quantity=Decimal("5"))

        for product in (self.p1, self.p2, self.p3):
            count = StockMovement.objects.filter(
                product=product, movement_type=MovementType.OUT,
            ).count()
            self.assertEqual(count, 1, f"Expected 1 OUT movement for {product.name}")

    def test_two_uses_of_same_product_in_one_surgery(self):
        """Two SurgeryUsedItem rows for the same product must each create
        an OUT movement and cumulatively decrease stock."""
        _used_item(self.surgery, self.p1, quantity=Decimal("10"))
        _used_item(self.surgery, self.p1, quantity=Decimal("15"))

        self.p1.refresh_from_db()
        self.assertEqual(self.p1.current_stock, Decimal("25"))  # 50 - 10 - 15

        movements = StockMovement.objects.filter(
            product=self.p1, movement_type=MovementType.OUT
        )
        self.assertEqual(movements.count(), 2)


# ---------------------------------------------------------------------------
# API-level: multiple used items via POST
# ---------------------------------------------------------------------------

class SurgeryUsedItemAPIMultipleTest(APITestCase):

    def setUp(self):
        self.user = User.objects.create_user(username="si_api_user", password="x")
        self.client.force_authenticate(self.user)

        self.surgery_type = _surgery_type()
        self.patient      = _patient()
        self.surgery      = _surgery(self.patient, self.surgery_type)
        self.p1 = _product(stock=Decimal("100"))
        self.p2 = _product(stock=Decimal("200"))

    def test_two_api_posts_decrease_two_products(self):
        url = "/api/v2/surgeries/used-items/"
        resp1 = self.client.post(url, {
            "surgery": self.surgery.id,
            "product": self.p1.id,
            "quantity": "30",
        })
        resp2 = self.client.post(url, {
            "surgery": self.surgery.id,
            "product": self.p2.id,
            "quantity": "50",
        })
        self.assertEqual(resp1.status_code, 201)
        self.assertEqual(resp2.status_code, 201)

        self.p1.refresh_from_db()
        self.p2.refresh_from_db()
        self.assertEqual(self.p1.current_stock, Decimal("70"))
        self.assertEqual(self.p2.current_stock, Decimal("150"))

    def test_insufficient_stock_on_second_item_leaves_first_intact(self):
        """If the second POST fails with insufficient stock, the first POST
        must already have been committed (each is its own transaction)."""
        url = "/api/v2/surgeries/used-items/"
        # First item: valid
        self.client.post(url, {
            "surgery": self.surgery.id,
            "product": self.p1.id,
            "quantity": "30",
        })
        # Second item: exceeds stock
        resp = self.client.post(url, {
            "surgery": self.surgery.id,
            "product": self.p2.id,
            "quantity": "999",
        })
        self.assertEqual(resp.status_code, 400)

        # First product was decreased
        self.p1.refresh_from_db()
        self.assertEqual(self.p1.current_stock, Decimal("70"))

        # Second product is unchanged
        self.p2.refresh_from_db()
        self.assertEqual(self.p2.current_stock, Decimal("200"))
