# Generated by Django 5.2.14 on 2026-05-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['purchase_price'], name='idx_product_purchase_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['current_stock'], name='idx_product_current_stock'),
        ),
    ]
