# Generated by Django 5.2.14 on 2026-05-25 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productvendor_unique_together_product_vendors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='همیشه مثبت. جهت تغییر موجودی از نوع حرکت تعیین می\u200cشود.', max_digits=12, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, default='', help_text='واحد اندازه\u200cگیری هنگام ثبت (برای تاریخچه). اگر خالی باشد از محصول کپی می\u200cشود.', max_length=50, verbose_name='واحد')),
                ('movement_type', models.CharField(choices=[('IN', 'ورود به انبار'), ('OUT', 'خروج از انبار'), ('ADJUSTMENT', 'تعدیل موجودی')], max_length=20, verbose_name='نوع حرکت')),
                ('source_type', models.CharField(choices=[('PURCHASE', 'خرید'), ('SURGERY_CONSUMPTION', 'مصرف در عمل جراحی'), ('MANUAL_ADJUSTMENT', 'تعدیل دستی'), ('RETURN', 'مرجوعی'), ('OTHER', 'سایر')], default='OTHER', max_length=30, verbose_name='منبع حرکت')),
                ('reference_id', models.CharField(blank=True, default='', help_text='شناسه شیء مرتبط (مثلاً شناسه فاکتور خرید یا عمل جراحی).', max_length=100, verbose_name='شناسه مرجع')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, help_text='زمان واقعی رویداد — ممکن است با تاریخ ثبت (created_at) متفاوت باشد.', verbose_name='تاریخ حرکت')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'حرکت موجودی',
                'verbose_name_plural': 'حرکات موجودی',
                'ordering': ['-movement_date', '-created_at'],
                'indexes': [models.Index(fields=['product'], name='idx_sm_product'), models.Index(fields=['movement_type'], name='idx_sm_movement_type'), models.Index(fields=['source_type'], name='idx_sm_source_type'), models.Index(fields=['movement_date'], name='idx_sm_movement_date'), models.Index(fields=['reference_id'], name='idx_sm_reference_id')],
            },
        ),
    ]
