# Generated by Django 5.2.14 on 2026-06-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchase_purchaseitem_purchase_idx_purchase_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvendor',
            name='unique_product_vendor',
        ),
    ]
