# Generated by Django 5.2.14 on 2026-08-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_unit_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('medicine', 'دارو'), ('equipment', 'تجهیزات')], help_text='یکی از انواع موجود را انتخاب کنید یا نوع جدیدی تایپ کنید.', max_length=50, verbose_name='نوع محصول'),
        ),
    ]
