# Generated by Django 5.2.14 on 2026-06-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_seed_expense_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
            ],
            options={
                'verbose_name': 'دسته\u200cبندی درآمد',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای درآمد',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.financecategory',),
        ),
    ]
