# Generated by Django 5.2.14 on 2026-08-20 15:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.productcategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصول',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('internal_code', models.CharField(max_length=50, unique=True, verbose_name='کد داخلی')),
                ('product_type', models.CharField(choices=[('medicine', 'دارو'), ('equipment', 'تجهیزات')], max_length=20, verbose_name='نوع محصول')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قیمت خرید')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قیمت فروش')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='بارکد')),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=12, verbose_name='موجودی فعلی')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='حداقل موجودی (هشدار)')),
                ('internal_notes', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام فروشنده')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مانده\u200cی اولیه\u200cای که کلینیک هنگام ثبت فروشنده به وی بدهکار/بستانکار بود.', max_digits=15, verbose_name='موجودی اولیه')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مانده\u200cی جاری حساب. مثبت: کلینیک بدهکار است. منفی: کلینیک طلبکار است.', max_digits=15, verbose_name='موجودی جاری')),
                ('tax_id', models.CharField(blank=True, default='', max_length=50, verbose_name='کد اقتصادی / شناسه مالیاتی')),
                ('bank_account', models.CharField(blank=True, default='', help_text='شماره شبا یا شماره حساب جاری برای پرداخت.', max_length=150, verbose_name='اطلاعات حساب بانکی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشندگان',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_vendor_is_active')],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, default='', help_text='شماره فاکتور یا شماره سفارش خرید.', max_length=100, verbose_name='شماره مرجع / فاکتور')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ خرید')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تأیید'), ('CONFIRMED', 'تأیید شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('stock_applied', models.BooleanField(default=False, editable=False, help_text='True پس از ایجاد حرکات موجودی. از اعمال دوباره جلوگیری می\u200cکند.', verbose_name='موجودی اعمال شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.vendor', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_product_name', models.CharField(blank=True, default='', help_text='نامی که فروشنده برای این محصول به\u200cکار می\u200cبرد.', max_length=255, verbose_name='نام محصول نزد فروشنده')),
                ('supplier_product_code', models.CharField(blank=True, default='', help_text='کد یا SKU فروشنده برای این محصول.', max_length=100, verbose_name='کد محصول نزد فروشنده')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قیمت واحد')),
                ('currency', models.CharField(default='IRR', help_text='کد ارز، مثلاً IRR، USD، EUR.', max_length=10, verbose_name='واحد پول')),
                ('last_price_date', models.DateField(blank=True, help_text='تاریخی که این قیمت آخرین بار تأیید یا به\u200cروز شد.', null=True, verbose_name='تاریخ آخرین قیمت')),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1, verbose_name='حداقل مقدار سفارش')),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='تعداد روزهای کاری تا تحویل سفارش.', verbose_name='مدت تحویل (روز)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='فروشنده اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendors', to='inventory.product', verbose_name='محصول')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendors', to='inventory.vendor', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'فروشنده محصول',
                'verbose_name_plural': 'فروشندگان محصول',
                'ordering': ['-is_primary', 'vendor__name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='products', through='inventory.ProductVendor', to='inventory.vendor', verbose_name='فروشندگان'),
        ),
        migrations.CreateModel(
            name='VendorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones', to='inventory.vendor')),
            ],
            options={
                'verbose_name': 'شماره تلفن دیگر',
                'verbose_name_plural': 'شماره\u200cهای تلفن دیگر',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, default='', help_text='اگر خالی باشد از محصول کپی می\u200cشود.', max_length=50, verbose_name='واحد')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قیمت واحد')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('manual_total', models.DecimalField(blank=True, decimal_places=2, help_text='اگر خالی باشد، جمع ردیف به\u200cصورت خودکار (مقدار × قیمت واحد) محاسبه می\u200cشود.', max_digits=14, null=True, verbose_name='جمع ردیف دستی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.product', verbose_name='محصول')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase', verbose_name='خرید')),
            ],
            options={
                'verbose_name': 'قلم خرید',
                'verbose_name_plural': 'اقلام خرید',
                'indexes': [models.Index(fields=['purchase'], name='idx_pi_purchase'), models.Index(fields=['product'], name='idx_pi_product')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='همیشه مثبت. جهت تغییر موجودی از نوع حرکت تعیین می\u200cشود.', max_digits=12, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, default='', help_text='واحد اندازه\u200cگیری هنگام ثبت (برای تاریخچه). اگر خالی باشد از محصول کپی می\u200cشود.', max_length=50, verbose_name='واحد')),
                ('movement_type', models.CharField(choices=[('IN', 'ورود به انبار'), ('OUT', 'خروج از انبار'), ('ADJUSTMENT', 'تعدیل موجودی')], max_length=20, verbose_name='نوع حرکت')),
                ('source_type', models.CharField(choices=[('PURCHASE', 'خرید'), ('SURGERY_CONSUMPTION', 'مصرف در عمل جراحی'), ('MANUAL_ADJUSTMENT', 'تعدیل دستی'), ('RETURN', 'مرجوعی'), ('OTHER', 'سایر')], default='OTHER', max_length=30, verbose_name='منبع حرکت')),
                ('reference_id', models.CharField(blank=True, default='', help_text='شناسه شیء مرتبط (مثلاً شناسه فاکتور خرید یا عمل جراحی).', max_length=100, verbose_name='شناسه مرجع')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, help_text='زمان واقعی رویداد — ممکن است با تاریخ ثبت (created_at) متفاوت باشد.', verbose_name='تاریخ حرکت')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'حرکت موجودی',
                'verbose_name_plural': 'حرکات موجودی',
                'ordering': ['-movement_date', '-created_at'],
                'indexes': [models.Index(fields=['product'], name='idx_sm_product'), models.Index(fields=['movement_type'], name='idx_sm_movement_type'), models.Index(fields=['source_type'], name='idx_sm_source_type'), models.Index(fields=['movement_date'], name='idx_sm_movement_date'), models.Index(fields=['reference_id'], name='idx_sm_reference_id')],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['vendor'], name='idx_purchase_vendor'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='idx_purchase_status'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date'], name='idx_purchase_date'),
        ),
        migrations.AddIndex(
            model_name='productvendor',
            index=models.Index(fields=['product'], name='idx_pv_product'),
        ),
        migrations.AddIndex(
            model_name='productvendor',
            index=models.Index(fields=['vendor'], name='idx_pv_vendor'),
        ),
        migrations.AddIndex(
            model_name='productvendor',
            index=models.Index(fields=['supplier_product_code'], name='idx_pv_supplier_code'),
        ),
        migrations.AddIndex(
            model_name='productvendor',
            index=models.Index(fields=['is_active'], name='idx_pv_is_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['internal_code'], name='idx_product_internal_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='idx_product_barcode'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='idx_product_type'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='idx_product_is_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['purchase_price'], name='idx_product_purchase_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['current_stock'], name='idx_product_current_stock'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode',), name='unique_barcode_when_set'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorphone',
            unique_together={('vendor', 'phone')},
        ),
    ]
