# Generated by Django 5.2.14 on 2026-05-24 20:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_root_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('internal_code', models.CharField(max_length=50, unique=True, verbose_name='کد داخلی')),
                ('product_type', models.CharField(choices=[('medicine', 'دارو'), ('equipment', 'تجهیزات')], max_length=20, verbose_name='نوع محصول')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قیمت خرید')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قیمت فروش')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='بارکد')),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=12, verbose_name='موجودی فعلی')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='حداقل موجودی (هشدار)')),
                ('internal_notes', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['internal_code'], name='idx_product_internal_code'), models.Index(fields=['barcode'], name='idx_product_barcode'), models.Index(fields=['product_type'], name='idx_product_type'), models.Index(fields=['is_active'], name='idx_product_is_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode',), name='unique_barcode_when_set')],
            },
        ),
    ]
