# Generated by Django 5.2.14 on 2026-05-25 18:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_idx_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام فروشنده')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مانده\u200cی اولیه\u200cای که کلینیک هنگام ثبت فروشنده به وی بدهکار/بستانکار بود.', max_digits=15, verbose_name='موجودی اولیه')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مانده\u200cی جاری حساب. مثبت: کلینیک بدهکار است. منفی: کلینیک طلبکار است.', max_digits=15, verbose_name='موجودی جاری')),
                ('tax_id', models.CharField(blank=True, default='', max_length=50, verbose_name='کد اقتصادی / شناسه مالیاتی')),
                ('bank_account', models.CharField(blank=True, default='', help_text='شماره شبا یا شماره حساب جاری برای پرداخت.', max_length=150, verbose_name='اطلاعات حساب بانکی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشندگان',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_vendor_is_active')],
            },
        ),
        migrations.CreateModel(
            name='ProductVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='فروشنده اصلی')),
                ('vendor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت خرید از فروشنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendors', to='inventory.product', verbose_name='محصول')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendors', to='inventory.vendor', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'فروشنده محصول',
                'verbose_name_plural': 'فروشندگان محصول',
                'ordering': ['-is_primary', 'vendor__name'],
                'unique_together': {('product', 'vendor')},
            },
        ),
    ]
