# Generated by Django 5.2.14 on 2026-05-25 19:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_vendor_productvendor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvendor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='products', through='inventory.ProductVendor', to='inventory.vendor', verbose_name='فروشندگان'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='currency',
            field=models.CharField(default='IRR', help_text='کد ارز، مثلاً IRR، USD، EUR.', max_length=10, verbose_name='واحد پول'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='last_price_date',
            field=models.DateField(blank=True, help_text='تاریخی که این قیمت آخرین بار تأیید یا به\u200cروز شد.', null=True, verbose_name='تاریخ آخرین قیمت'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='تعداد روزهای کاری تا تحویل سفارش.', verbose_name='مدت تحویل (روز)'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='حداقل مقدار سفارش'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='supplier_product_code',
            field=models.CharField(blank=True, default='', help_text='کد یا SKU فروشنده برای این محصول.', max_length=100, verbose_name='کد محصول نزد فروشنده'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='supplier_product_name',
            field=models.CharField(blank=True, default='', help_text='نامی که فروشنده برای این محصول به\u200cکار می\u200cبرد.', max_length=255, verbose_name='نام محصول نزد فروشنده'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قیمت واحد'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AddIndex(
            model_name='productvendor',
            index=models.Index(fields=['product'], name='idx_pv_product'),
        ),
        migrations.AddIndex(
            model_name='productvendor',
            index=models.Index(fields=['vendor'], name='idx_pv_vendor'),
        ),
        migrations.AddIndex(
            model_name='productvendor',
            index=models.Index(fields=['supplier_product_code'], name='idx_pv_supplier_code'),
        ),
        migrations.AddIndex(
            model_name='productvendor',
            index=models.Index(fields=['is_active'], name='idx_pv_is_active'),
        ),
        migrations.AddConstraint(
            model_name='productvendor',
            constraint=models.UniqueConstraint(fields=('product', 'vendor'), name='unique_product_vendor'),
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='vendor_price',
        ),
    ]
