# Generated by Django 5.2.14 on 2026-07-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_vendorphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='واحد اندازه\u200cگیری'),
        ),
    ]
