# Generated by Django 5.2.14 on 2026-06-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_doctorcontact_rate_per_surgery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcontact',
            name='rate_per_surgery',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ ثابت دستمزد پزشک به ازای هر عمل. می\u200cتواند برای هر پزشک متفاوت باشد.', max_digits=14, null=True, verbose_name='نرخ هر عمل (تومان)'),
        ),
    ]
