# Generated by Django 5.2.14 on 2026-07-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_doctor_document_images'),
        ('surgeries', '0014_alter_surgerytype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSurgeryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='نرخ هر عمل (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_rates', to='contacts.doctor', verbose_name='پزشک')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_rates', to='surgeries.surgerytype', verbose_name='نوع عمل')),
            ],
            options={
                'verbose_name': 'نرخ پزشک به ازای نوع عمل',
                'verbose_name_plural': 'نرخ\u200cهای پزشک به تفکیک نوع عمل',
                'ordering': ['doctor__full_name', 'surgery_type__name'],
                'unique_together': {('doctor', 'surgery_type')},
            },
        ),
    ]
