# Generated by Django 5.2.14 on 2026-05-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_seed_job_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('month', models.PositiveIntegerField(verbose_name='ماه')),
                ('status', models.CharField(choices=[('OPEN', 'باز'), ('CLOSED', 'بسته'), ('PROCESSED', 'پردازش\u200cشده')], default='OPEN', max_length=10, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن')),
            ],
            options={
                'verbose_name': 'دوره حقوقی',
                'verbose_name_plural': 'دوره\u200cهای حقوقی',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_monthly_wage', models.BooleanField(default=False, verbose_name='دارای حقوق ثابت')),
                ('has_commission', models.BooleanField(default=False, verbose_name='دارای کمیسیون')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'تنظیمات حقوقی',
                'verbose_name_plural': 'تنظیمات حقوقی',
            },
        ),
    ]
