# Generated by Django 5.2.14 on 2026-06-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_hourly_rate_purchase_commission'),
        ('payroll', '0006_commission_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalali_year', models.PositiveIntegerField(verbose_name='سال شمسی')),
                ('jalali_month', models.PositiveIntegerField(verbose_name='ماه شمسی')),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='کل ساعات کاری در این ماه', max_digits=7, verbose_name='ساعات کاری')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='نرخ ساعتی اعمال\u200cشده برای این ماه — برای حفظ تاریخچه snapshot می\u200cشود.', max_digits=14, verbose_name='نرخ هر ساعت (تومان)')),
                ('calculated_salary', models.DecimalField(decimal_places=2, editable=False, help_text='= ساعات کاری × نرخ هر ساعت', max_digits=14, verbose_name='حقوق محاسبه\u200cشده (تومان)')),
                ('record_date', models.DateField(editable=False, help_text='اولین روز ماه شمسی به میلادی — برای فیلتر بازه تاریخ', verbose_name='تاریخ دوره (میلادی)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_work_records', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'رکورد ساعات کاری ماهانه',
                'verbose_name_plural': 'رکوردهای ساعات کاری ماهانه',
                'ordering': ['-jalali_year', '-jalali_month'],
                'indexes': [models.Index(fields=['employee'], name='idx_hwr_employee'), models.Index(fields=['record_date'], name='idx_hwr_record_date')],
                'unique_together': {('employee', 'jalali_year', 'jalali_month')},
            },
        ),
    ]
