# Generated by Django 5.2.14 on 2026-08-21 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0011_doctor_specialty_phone_optional'),
        ('surgeries', '0021_alter_patient_case_code_alter_patient_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, default='', max_length=200, verbose_name='نام بیمار (در صورت نبودن در سیستم)')),
                ('patient_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تماس بیمار')),
                ('visit_date', models.DateField(verbose_name='تاریخ ویزیت')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='مدت (دقیقه)')),
                ('status', models.CharField(choices=[('SCHEDULED', 'برنامه\u200cریزی\u200cشده'), ('COMPLETED', 'انجام\u200cشده'), ('CANCELLED', 'لغو شده'), ('NO_SHOW', 'عدم مراجعه')], default='SCHEDULED', max_length=10, verbose_name='وضعیت')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='علت مراجعه')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='contacts.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(blank=True, help_text='در صورت خالی بودن، از نام و شماره تماس زیر استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='surgeries.patient', verbose_name='بیمار (ثبت\u200cشده)')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['visit_date', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'visit_date'], name='idx_appt_doctor_date'), models.Index(fields=['visit_date'], name='idx_appt_date')],
            },
        ),
    ]
