# Generated by Django 5.2.14 on 2026-08-20 15:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '__first__'),
        ('employees', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnesthesiaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام نوع بیهوشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'نوع بیهوشی',
                'verbose_name_plural': 'انواع بیهوشی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(blank=True, default='', max_length=20, verbose_name='کد ملی')),
                ('case_code', models.CharField(help_text='کد پرونده باید منحصربه\u200cفرد باشد.', max_length=50, unique=True, verbose_name='کد پرونده')),
                ('internal_code', models.CharField(blank=True, help_text='اختیاری — در صورت تکمیل، باید منحصربه\u200cفرد باشد.', max_length=50, null=True, verbose_name='کد داخلی بیمار')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(130, message='سن باید حداکثر ۱۳۰ سال باشد.')], verbose_name='سن بیمار')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('is_hidden', models.BooleanField(default=False, help_text='بیمار مخفی فقط برای مدیر اصلی سیستم قابل مشاهده است.', verbose_name='مخفی')),
                ('hidden_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان مخفی\u200cسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مخفی\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='نام بیمار')),
                ('surgery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عمل')),
                ('surgeon_name', models.CharField(blank=True, default='', help_text='تا پیاده\u200cسازی مدل Employee این فیلد متن آزاد است.', max_length=200, verbose_name='نام جراح')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('status', models.CharField(choices=[('PLANNED', 'برنامه\u200cریزی شده'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'انجام شده'), ('CANCELLED', 'لغو شده')], default='PLANNED', max_length=20, verbose_name='وضعیت')),
                ('stock_applied', models.BooleanField(default=False, editable=False, help_text='True پس از ایجاد حرکات موجودی OUT. از اعمال دوباره جلوگیری می\u200cکند.', verbose_name='موجودی اعمال شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'عمل جراحی',
                'verbose_name_plural': 'اعمال جراحی',
                'ordering': ['-surgery_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_surgery_status'), models.Index(fields=['surgery_date'], name='idx_surgery_date')],
            },
        ),
        migrations.CreateModel(
            name='SurgeryConsumptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار مصرف')),
                ('unit', models.CharField(blank=True, default='', help_text='اگر خالی باشد از محصول کپی می\u200cشود.', max_length=50, verbose_name='واحد')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_consumption_items', to='inventory.product', verbose_name='محصول')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_items', to='surgeries.surgery', verbose_name='عمل جراحی')),
            ],
            options={
                'verbose_name': 'قلم مصرف جراحی',
                'verbose_name_plural': 'اقلام مصرف جراحی',
            },
        ),
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام عمل')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='نرخ پایه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'نوع عمل جراحی',
                'verbose_name_plural': 'انواع عمل جراحی',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='surgeries_s_code_d4cf1f_idx'), models.Index(fields=['is_active'], name='surgeries_s_is_acti_bddf1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurgeryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(help_text='کد پرونده بیمار هنگام ثبت (کپی از بیمار برای آرشیو).', max_length=50, verbose_name='ردیف')),
                ('medical_record_code', models.CharField(blank=True, default='', help_text='کد پرونده پزشکی مربوط به این عمل جراحی.', max_length=50, verbose_name='کد پرونده')),
                ('phone_number', models.CharField(help_text='شماره تماس هنگام ثبت (کپی از بیمار برای آرشیو).', max_length=20, verbose_name='شماره تلفن')),
                ('surgery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عمل')),
                ('surgery_start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع عمل')),
                ('surgery_end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت اتمام عمل')),
                ('postoperative_diagnosis', models.TextField(blank=True, default='', verbose_name='تشخیص بعد از عمل')),
                ('operation_description', models.TextField(blank=True, default='', verbose_name='شرح عمل و مشاهدات')),
                ('amount', models.DecimalField(decimal_places=2, help_text='هزینه عمل جراحی به تومان.', max_digits=14, verbose_name='مبلغ')),
                ('payment_status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PARTIAL', 'پرداخت ناقص'), ('PAID', 'پرداخت شده')], default='PENDING', max_length=10, verbose_name='وضعیت پرداخت')),
                ('center_commission_percent', models.DecimalField(blank=True, decimal_places=2, help_text='درصد سهم مرکز از مبلغ عمل (۰ تا ۱۰۰).', max_digits=5, null=True, verbose_name='درصد کمیسیون مرکز')),
                ('center_commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ ثابت سهم مرکز. اگر تنظیم شود، بر درصد اولویت دارد.', max_digits=14, null=True, verbose_name='مبلغ کمیسیون مرکز')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('PLANNED', 'برنامه\u200cریزی شده'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'انجام شده'), ('CANCELLED', 'لغو شده')], default='PLANNED', max_length=20, verbose_name='وضعیت عمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('anesthesia_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesia_technician_surgeries', to='employees.employee', verbose_name='تکنسین بیهوشی')),
                ('anesthesia_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surgery_histories', to='surgeries.anesthesiatype', verbose_name='نوع بیهوشی')),
                ('anesthesiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesiologist_surgeries', to='employees.employee', verbose_name='متخصص بیهوشی')),
                ('assistant_surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_surgeon_surgeries', to='employees.employee', verbose_name='کمک اول جراح')),
                ('circulator_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulator_surgeries', to='employees.employee', verbose_name='سیرکولر')),
                ('clinical_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_histories', to='contacts.doctor', verbose_name='نام جراح/درمانگر')),
                ('doctor_or_therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_histories', to='employees.employee', verbose_name='کارمند درمانگر (برای محاسبه کمیسیون)')),
                ('operating_room_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_room_manager_surgeries', to='employees.employee', verbose_name='مسئول اتاق عمل')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_histories', to='surgeries.patient', verbose_name='بیمار')),
                ('scrub_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrub_surgeries', to='employees.employee', verbose_name='اسکراب')),
                ('second_assistant_surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_assistant_surgeries', to='employees.employee', verbose_name='کمک دوم جراح')),
                ('service_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_surgeries', to='employees.employee', verbose_name='خدمات')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_histories', to='surgeries.surgerytype', verbose_name='نوع عمل')),
            ],
            options={
                'verbose_name': 'تاریخچه عمل جراحی',
                'verbose_name_plural': 'تاریخچه اعمال جراحی',
                'ordering': ['-surgery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryUsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, default='', help_text='اگر خالی باشد از محصول کپی می\u200cشود.', max_length=50, verbose_name='واحد')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_used_items', to='inventory.product', verbose_name='محصول / کالا')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_items', to='surgeries.surgeryhistory', verbose_name='تاریخچه عمل جراحی')),
            ],
            options={
                'verbose_name': 'قلم مصرف تاریخچه عمل',
                'verbose_name_plural': 'اقلام مصرف تاریخچه عمل',
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['case_code'], name='idx_patient_case_code'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['internal_code'], name='idx_patient_internal_code'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='idx_patient_phone'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_code__isnull', False), models.Q(('internal_code', ''), _negated=True)), fields=('internal_code',), name='unique_patient_internal_code_when_set', violation_error_message='کد داخلی بیمار باید یکتا باشد.'),
        ),
        migrations.AddIndex(
            model_name='surgeryconsumptionitem',
            index=models.Index(fields=['surgery'], name='idx_sci_surgery'),
        ),
        migrations.AddIndex(
            model_name='surgeryconsumptionitem',
            index=models.Index(fields=['product'], name='idx_sci_product'),
        ),
        migrations.AddIndex(
            model_name='surgeryhistory',
            index=models.Index(fields=['patient'], name='idx_sh_patient'),
        ),
        migrations.AddIndex(
            model_name='surgeryhistory',
            index=models.Index(fields=['surgery_type'], name='idx_sh_surgery_type'),
        ),
        migrations.AddIndex(
            model_name='surgeryhistory',
            index=models.Index(fields=['surgery_date'], name='idx_sh_surgery_date'),
        ),
        migrations.AddIndex(
            model_name='surgeryhistory',
            index=models.Index(fields=['status'], name='idx_sh_status'),
        ),
        migrations.AddIndex(
            model_name='surgeryhistory',
            index=models.Index(fields=['payment_status'], name='idx_sh_payment_status'),
        ),
        migrations.AddIndex(
            model_name='surgeryuseditem',
            index=models.Index(fields=['surgery'], name='idx_sui_surgery'),
        ),
        migrations.AddIndex(
            model_name='surgeryuseditem',
            index=models.Index(fields=['product'], name='idx_sui_product'),
        ),
    ]
