# Generated by Django 5.2.14 on 2026-05-25 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0008_purchase_purchaseitem_purchase_idx_purchase_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='نام بیمار')),
                ('surgery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عمل')),
                ('surgeon_name', models.CharField(blank=True, default='', help_text='تا پیاده\u200cسازی مدل Employee این فیلد متن آزاد است.', max_length=200, verbose_name='نام جراح')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('status', models.CharField(choices=[('PLANNED', 'برنامه\u200cریزی شده'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'انجام شده'), ('CANCELLED', 'لغو شده')], default='PLANNED', max_length=20, verbose_name='وضعیت')),
                ('stock_applied', models.BooleanField(default=False, editable=False, help_text='True پس از ایجاد حرکات موجودی OUT. از اعمال دوباره جلوگیری می\u200cکند.', verbose_name='موجودی اعمال شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'عمل جراحی',
                'verbose_name_plural': 'اعمال جراحی',
                'ordering': ['-surgery_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_surgery_status'), models.Index(fields=['surgery_date'], name='idx_surgery_date')],
            },
        ),
        migrations.CreateModel(
            name='SurgeryConsumptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار مصرف')),
                ('unit', models.CharField(blank=True, default='', help_text='اگر خالی باشد از محصول کپی می\u200cشود.', max_length=50, verbose_name='واحد')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_consumption_items', to='inventory.product', verbose_name='محصول')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_items', to='surgeries.surgery', verbose_name='عمل جراحی')),
            ],
            options={
                'verbose_name': 'قلم مصرف جراحی',
                'verbose_name_plural': 'اقلام مصرف جراحی',
                'indexes': [models.Index(fields=['surgery'], name='idx_sci_surgery'), models.Index(fields=['product'], name='idx_sci_product')],
            },
        ),
    ]
