# Generated by Django 5.2.14 on 2026-06-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_seed_job_positions'),
        ('surgeries', '0008_patient_national_id_phone_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryhistory',
            name='doctor_or_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_histories', to='employees.employee', verbose_name='پزشک معالج'),
        ),
    ]
