# Generated by Django 5.2.14 on 2026-06-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_doctorcontact_rate_per_surgery'),
        ('surgeries', '0009_doctor_or_therapist_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryhistory',
            name='doctor_or_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_histories', to='contacts.doctorcontact', verbose_name='پزشک معالج'),
        ),
    ]
