# Generated by Django 5.2.14 on 2026-07-09 00:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_doctorsurgeryrate'),
        ('employees', '0004_employee_hourly_rate_purchase_commission'),
        ('surgeries', '0014_alter_surgerytype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnesthesiaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام نوع بیهوشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'نوع بیهوشی',
                'verbose_name_plural': 'انواع بیهوشی',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='anesthesia_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesia_technician_surgeries', to='employees.employee', verbose_name='تکنسین بیهوشی'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='anesthesiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesiologist_surgeries', to='employees.employee', verbose_name='متخصص بیهوشی'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='assistant_surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_surgeon_surgeries', to='employees.employee', verbose_name='کمک اول جراح'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='circulator_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulator_surgeries', to='employees.employee', verbose_name='سیرکولر'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='operating_room_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_room_manager_surgeries', to='employees.employee', verbose_name='مسئول اتاق عمل'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='operation_description',
            field=models.TextField(blank=True, default='', verbose_name='شرح عمل و مشاهدات'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='postoperative_diagnosis',
            field=models.TextField(blank=True, default='', verbose_name='تشخیص بعد از عمل'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='scrub_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrub_surgeries', to='employees.employee', verbose_name='اسکراب'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='second_assistant_surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_assistant_surgeries', to='contacts.doctor', verbose_name='کمک دوم جراح'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='service_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_surgeries', to='employees.employee', verbose_name='خدمات'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='surgery_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت اتمام عمل'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='surgery_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت شروع عمل'),
        ),
        migrations.AlterField(
            model_name='surgeryhistory',
            name='clinical_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_histories', to='contacts.doctor', verbose_name='نام جراح/درمانگر'),
        ),
        migrations.AlterField(
            model_name='surgeryhistory',
            name='surgery_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عمل'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='anesthesia_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surgery_histories', to='surgeries.anesthesiatype', verbose_name='نوع بیهوشی'),
        ),
    ]
