# Generated by Django 5.2.14 on 2026-07-16 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0016_patient_internal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان مخفی\u200cسازی'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مخفی\u200cشده توسط'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='بیمار مخفی فقط برای مدیر اصلی سیستم قابل مشاهده است.', verbose_name='مخفی'),
        ),
    ]
