# Generated by Django 5.2.14 on 2026-08-20 15:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('surgeries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد کمیسیون')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ شروع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_rules', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_rules', to='employees.jobposition', verbose_name='موقعیت شغلی')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_rules', to='surgeries.surgerytype', verbose_name='نوع عمل')),
            ],
            options={
                'verbose_name': 'قانون کمیسیون',
                'verbose_name_plural': 'قوانین کمیسیون',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ کمیسیون = مبلغ عمل × درصد کمیسیون / ۱۰۰', max_digits=14, verbose_name='مبلغ کمیسیون')),
                ('notes', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('commission_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payroll.commissionrule', verbose_name='قانون کمیسیون')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_transactions', to='employees.employee', verbose_name='کارمند')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_transactions', to='surgeries.surgeryhistory', verbose_name='تاریخچه عمل')),
            ],
            options={
                'verbose_name': 'تراکنش کمیسیون',
                'verbose_name_plural': 'تراکنش\u200cهای کمیسیون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='نرخ هر ساعت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hourly_rates', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_rates', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'نرخ ساعتی',
                'verbose_name_plural': 'نرخ\u200cهای ساعتی',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HourlyWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalali_year', models.PositiveIntegerField(verbose_name='سال شمسی')),
                ('jalali_month', models.PositiveIntegerField(verbose_name='ماه شمسی')),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='کل ساعات کاری در این ماه', max_digits=7, verbose_name='ساعات کاری')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='نرخ ساعتی اعمال\u200cشده برای این ماه — برای حفظ تاریخچه snapshot می\u200cشود.', max_digits=14, verbose_name='نرخ هر ساعت (تومان)')),
                ('calculated_salary', models.DecimalField(decimal_places=2, editable=False, help_text='= ساعات کاری × نرخ هر ساعت', max_digits=14, verbose_name='حقوق محاسبه\u200cشده (تومان)')),
                ('record_date', models.DateField(editable=False, help_text='اولین روز ماه شمسی به میلادی — برای فیلتر بازه تاریخ', verbose_name='تاریخ دوره (میلادی)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_work_records', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'رکورد ساعات کاری ماهانه',
                'verbose_name_plural': 'رکوردهای ساعات کاری ماهانه',
                'ordering': ['-jalali_year', '-jalali_month'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ حقوق')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wages', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_wages', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'حقوق ماهیانه',
                'verbose_name_plural': 'حقوق ماهیانه',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('month', models.PositiveIntegerField(verbose_name='ماه')),
                ('status', models.CharField(choices=[('OPEN', 'باز'), ('CLOSED', 'بسته'), ('PROCESSED', 'پردازش\u200cشده')], default='OPEN', max_length=10, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن')),
            ],
            options={
                'verbose_name': 'دوره حقوقی',
                'verbose_name_plural': 'دوره\u200cهای حقوقی',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='HourlyWorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='تاریخ کار')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ساعات کارکرد')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('rate_used', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='نرخ ساعتی مؤثر در تاریخ کار — هنگام محاسبه حقوق snapshot می\u200cشود.', max_digits=14, null=True, verbose_name='نرخ اعمال\u200cشده')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='= ساعات کارکرد × نرخ اعمال\u200cشده', max_digits=14, null=True, verbose_name='مبلغ محاسبه\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_work_entries', to='employees.employee', verbose_name='کارمند')),
                ('payroll_period', models.ForeignKey(blank=True, help_text='پس از محاسبه حقوق ساعتی این دوره، به\u200cطور خودکار تکمیل می\u200cشود.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hourly_work_entries', to='payroll.payrollperiod', verbose_name='دوره حقوقی')),
            ],
            options={
                'verbose_name': 'رکورد ساعت کاری',
                'verbose_name_plural': 'رکوردهای ساعت کاری',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_monthly_wage', models.BooleanField(default=False, verbose_name='دارای حقوق ثابت')),
                ('has_commission', models.BooleanField(default=False, verbose_name='دارای کمیسیون')),
                ('has_hourly_wage', models.BooleanField(default=False, verbose_name='دارای حقوق ساعتی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'تنظیمات حقوقی',
                'verbose_name_plural': 'تنظیمات حقوقی',
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['job_position'], name='payroll_com_job_pos_0e80ba_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['surgery_type'], name='payroll_com_surgery_3a2a17_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['is_active'], name='payroll_com_is_acti_b94058_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['surgery'], name='idx_ct_surgery'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['employee'], name='idx_ct_employee'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['created_at'], name='idx_ct_created_at'),
        ),
        migrations.AddConstraint(
            model_name='commissiontransaction',
            constraint=models.UniqueConstraint(fields=('surgery', 'employee', 'commission_rule'), name='unique_surgery_employee_rule'),
        ),
        migrations.AddIndex(
            model_name='hourlyrate',
            index=models.Index(fields=['employee'], name='payroll_hou_employe_abbe4f_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyrate',
            index=models.Index(fields=['is_active'], name='payroll_hou_is_acti_9dc145_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyrate',
            index=models.Index(fields=['start_date'], name='payroll_hou_start_d_a6654a_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyworkrecord',
            index=models.Index(fields=['employee'], name='idx_hwr_employee'),
        ),
        migrations.AddIndex(
            model_name='hourlyworkrecord',
            index=models.Index(fields=['record_date'], name='idx_hwr_record_date'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlyworkrecord',
            unique_together={('employee', 'jalali_year', 'jalali_month')},
        ),
        migrations.AddIndex(
            model_name='monthlywage',
            index=models.Index(fields=['employee'], name='payroll_mon_employe_9482ae_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlywage',
            index=models.Index(fields=['is_active'], name='payroll_mon_is_acti_d9fb12_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlywage',
            index=models.Index(fields=['start_date'], name='payroll_mon_start_d_f73098_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyworkentry',
            index=models.Index(fields=['employee'], name='payroll_hou_employe_d41b07_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyworkentry',
            index=models.Index(fields=['work_date'], name='payroll_hou_work_da_3c7c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyworkentry',
            index=models.Index(fields=['payroll_period'], name='payroll_hou_payroll_425155_idx'),
        ),
    ]
