# Generated by Django 5.2.14 on 2026-05-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrolltypeconfig',
            options={'ordering': ['employee__full_name'], 'verbose_name': 'تنظیمات حقوقی', 'verbose_name_plural': 'تنظیمات حقوقی'},
        ),
    ]
