# Generated by Django 5.2.14 on 2026-05-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_seed_job_positions'),
        ('payroll', '0002_alter_payrolltypeconfig_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ حقوق')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wages', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_wages', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'حقوق ماهیانه',
                'verbose_name_plural': 'حقوق ماهیانه',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee'], name='payroll_mon_employe_9482ae_idx'), models.Index(fields=['is_active'], name='payroll_mon_is_acti_d9fb12_idx'), models.Index(fields=['start_date'], name='payroll_mon_start_d_f73098_idx')],
            },
        ),
    ]
