# Generated by Django 5.2.14 on 2026-05-28 15:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_seed_job_positions'),
        ('payroll', '0003_monthlywage'),
        ('surgeries', '0003_seed_surgery_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlywage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wages', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد کمیسیون')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ شروع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_rules', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_rules', to='employees.jobposition', verbose_name='موقعیت شغلی')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_rules', to='surgeries.surgerytype', verbose_name='نوع عمل')),
            ],
            options={
                'verbose_name': 'قانون کمیسیون',
                'verbose_name_plural': 'قوانین کمیسیون',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['job_position'], name='payroll_com_job_pos_0e80ba_idx'), models.Index(fields=['surgery_type'], name='payroll_com_surgery_3a2a17_idx'), models.Index(fields=['is_active'], name='payroll_com_is_acti_b94058_idx')],
            },
        ),
    ]
