# Generated by Django 5.2.14 on 2026-07-11 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_hourly_rate_purchase_commission'),
        ('payroll', '0007_hourly_work_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolltypeconfig',
            name='has_hourly_wage',
            field=models.BooleanField(default=False, verbose_name='دارای حقوق ساعتی'),
        ),
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='نرخ هر ساعت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hourly_rates', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_rates', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'نرخ ساعتی',
                'verbose_name_plural': 'نرخ\u200cهای ساعتی',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee'], name='payroll_hou_employe_abbe4f_idx'), models.Index(fields=['is_active'], name='payroll_hou_is_acti_9dc145_idx'), models.Index(fields=['start_date'], name='payroll_hou_start_d_a6654a_idx')],
            },
        ),
        migrations.CreateModel(
            name='HourlyWorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='تاریخ کار')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ساعات کارکرد')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('rate_used', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='نرخ ساعتی مؤثر در تاریخ کار — هنگام محاسبه حقوق snapshot می\u200cشود.', max_digits=14, null=True, verbose_name='نرخ اعمال\u200cشده')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='= ساعات کارکرد × نرخ اعمال\u200cشده', max_digits=14, null=True, verbose_name='مبلغ محاسبه\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_work_entries', to='employees.employee', verbose_name='کارمند')),
                ('payroll_period', models.ForeignKey(blank=True, help_text='پس از محاسبه حقوق ساعتی این دوره، به\u200cطور خودکار تکمیل می\u200cشود.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hourly_work_entries', to='payroll.payrollperiod', verbose_name='دوره حقوقی')),
            ],
            options={
                'verbose_name': 'رکورد ساعت کاری',
                'verbose_name_plural': 'رکوردهای ساعت کاری',
                'ordering': ['-work_date'],
                'indexes': [models.Index(fields=['employee'], name='payroll_hou_employe_d41b07_idx'), models.Index(fields=['work_date'], name='payroll_hou_work_da_3c7c3d_idx'), models.Index(fields=['payroll_period'], name='payroll_hou_payroll_425155_idx')],
            },
        ),
    ]
