# Generated by Django 5.2.14 on 2026-06-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0006_surgery_used_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryhistory',
            name='center_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ ثابت سهم مرکز. اگر تنظیم شود، بر درصد اولویت دارد.', max_digits=14, null=True, verbose_name='مبلغ کمیسیون مرکز'),
        ),
        migrations.AddField(
            model_name='surgeryhistory',
            name='center_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد سهم مرکز از مبلغ عمل (۰ تا ۱۰۰).', max_digits=5, null=True, verbose_name='درصد کمیسیون مرکز'),
        ),
    ]
