# Generated by Django 5.2.14 on 2026-06-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_doctorcontact_rate_per_surgery'),
        ('employees', '0003_seed_job_positions'),
        ('surgeries', '0010_surgeryhistory_doctor_to_doctorcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryhistory',
            name='clinical_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_histories', to='contacts.doctorcontact', verbose_name='پزشک معالج'),
        ),
        migrations.AlterField(
            model_name='surgeryhistory',
            name='doctor_or_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_histories', to='employees.employee', verbose_name='کارمند درمانگر (برای محاسبه کمیسیون)'),
        ),
    ]
