# Generated by Django 5.2.14 on 2026-06-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0011_add_clinical_doctor_revert_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='هزینه عمل جراحی به تومان.', max_digits=14, verbose_name='مبلغ'),
        ),
    ]
