# Generated by Django 5.2.14 on 2026-07-06 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0012_alter_surgeryhistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryhistory',
            name='medical_record_code',
            field=models.CharField(blank=True, default='', help_text='کد پرونده پزشکی مربوط به این عمل جراحی.', max_length=50, verbose_name='کد پرونده'),
        ),
        migrations.AlterField(
            model_name='surgeryhistory',
            name='case_code',
            field=models.CharField(help_text='کد پرونده بیمار هنگام ثبت (کپی از بیمار برای آرشیو).', max_length=50, verbose_name='ردیف'),
        ),
        migrations.AlterField(
            model_name='surgeryhistory',
            name='surgery_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
        ),
    ]
