# Generated by Django 5.2.14 on 2026-07-17 15:00

import django.db.models.deletion
from django.db import migrations, models


def clear_stale_second_assistant_surgeon(apps, schema_editor):
    """second_assistant_surgeon is switching from a Doctor FK to an Employee
    FK — Doctor and Employee have unrelated pk sequences, so any existing
    value is a Doctor id that would silently become a wrong (or
    constraint-violating) Employee reference once the column's target
    changes. There is no meaningful way to "translate" a Doctor id into the
    correct Employee id, so any pre-existing assignment is cleared here
    (field is nullable/optional, so this is a safe no-op wherever nothing
    was ever set — confirmed zero non-null rows in this project's own dev
    data at the time this migration was written).
    """
    SurgeryHistory = apps.get_model('surgeries', 'SurgeryHistory')
    SurgeryHistory.objects.exclude(second_assistant_surgeon_id__isnull=True).update(
        second_assistant_surgeon_id=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_employee_credential_images'),
        ('surgeries', '0017_patient_hidden_at_patient_hidden_by_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_stale_second_assistant_surgeon, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='surgeryhistory',
            name='second_assistant_surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_assistant_surgeries', to='employees.employee', verbose_name='کمک دوم جراح'),
        ),
    ]
