# Generated by Django 5.2.14 on 2026-07-17 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0017_patient_hidden_at_patient_hidden_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(130, message='سن باید حداکثر ۱۳۰ سال باشد.')], verbose_name='سن بیمار'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
    ]
