# Generated by Django 5.2.14 on 2026-08-20 15:54

import common.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(help_text='کد ملی باید منحصربه\u200cفرد باشد.', max_length=20, unique=True, verbose_name='کد ملی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, verbose_name='جنسیت')),
                ('start_date', models.DateField(verbose_name='تاریخ استخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('personal_phone', models.CharField(max_length=20, verbose_name='تلفن شخصی')),
                ('emergency_contact_phone', models.CharField(help_text='شماره تماس در مواقع اضطراری (مثلاً خانواده).', max_length=20, verbose_name='تلفن اضطراری')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='بخشی از سامانه قدیمی حقوق ساعتی — فقط برای سازگاری با رکوردهای قبلی («رکوردهای ساعات کاری ماهانه») نگه داشته شده و برای کارمندان جدید استفاده نمی\u200cشود.', max_digits=14, null=True, verbose_name='نرخ هر ساعت (قدیمی / بایگانی)')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات / یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام پوزیشن')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'پوزیشن شغلی',
                'verbose_name_plural': 'پوزیشن\u200cهای شغلی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=common.uploads.employee_document_upload_path, validators=[common.uploads.validate_image_upload], verbose_name='مدرک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'مدرک کارمند',
                'verbose_name_plural': 'مدارک کارمند',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobposition', verbose_name='سمت / عنوان شغلی'),
        ),
        migrations.CreateModel(
            name='EmployeePurchaseCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ کمیسیون (تومان)')),
                ('commission_date', models.DateField(verbose_name='تاریخ کمیسیون')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات / دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_commissions', to='employees.employee', verbose_name='کارمند')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_commissions', to='inventory.purchase', verbose_name='فاکتور خرید')),
            ],
            options={
                'verbose_name': 'کمیسیون خرید',
                'verbose_name_plural': 'کمیسیون\u200cهای خرید',
                'ordering': ['-commission_date'],
                'indexes': [models.Index(fields=['employee'], name='idx_epc_employee'), models.Index(fields=['commission_date'], name='idx_epc_date')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='idx_emp_is_active'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['start_date'], name='idx_emp_start_date'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['national_id'], name='idx_emp_national_id'),
        ),
    ]
