# Generated by Django 5.2.14 on 2026-07-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_hourly_rate'),
        ('employees', '0005_employee_credential_image_1_and_more'),
    ]

    operations = [
    ]
