# Generated by Django 5.2.14 on 2026-07-12 13:53

import common.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_merge_hourly_rate_and_documents'),
    ]

    operations = [
        # credential_image_1 / credential_image_2 are intentionally NOT
        # removed here — migration 0008 copies any pre-existing non-empty
        # values into EmployeeDocument first, then migration 0009 removes
        # the fields. Removing them in this same migration (as the
        # autodetector suggested) would delete the columns before that data
        # migration ever gets to read them.
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=common.uploads.employee_document_upload_path, validators=[common.uploads.validate_image_upload], verbose_name='مدرک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'مدرک کارمند',
                'verbose_name_plural': 'مدارک کارمند',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
