# Generated by Django 5.2.14 on 2026-08-20 15:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ باید بزرگ\u200cتر از صفر باشد.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'هزینه متفرقه',
                'verbose_name_plural': 'هزینه\u200cهای متفرقه',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
