# Generated by Django 5.2.14 on 2026-05-24 17:20

from django.db import migrations


def seed_root_categories(apps, schema_editor):
    """Create the two fixed root categories if they don't already exist.

    get_or_create makes this idempotent — safe to run on an existing
    database (e.g. restored backup, re-run after a failed deploy).
    """
    ProductCategory = apps.get_model("inventory", "ProductCategory")
    ProductCategory.objects.get_or_create(
        name="دارو",
        parent=None,
        defaults={"is_active": True},
    )
    ProductCategory.objects.get_or_create(
        name="تجهیزات",
        parent=None,
        defaults={"is_active": True},
    )


def remove_root_categories(apps, schema_editor):
    """Reverse: remove only the seeded roots (leave any user-created ones)."""
    ProductCategory = apps.get_model("inventory", "ProductCategory")
    ProductCategory.objects.filter(name__in=["دارو", "تجهیزات"], parent=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_root_categories, reverse_code=remove_root_categories),
    ]
