# Generated by Django 5.2.14 on 2026-05-25 20:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, default='', help_text='شماره فاکتور یا شماره سفارش خرید.', max_length=100, verbose_name='شماره مرجع / فاکتور')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ خرید')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تأیید'), ('CONFIRMED', 'تأیید شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('stock_applied', models.BooleanField(default=False, editable=False, help_text='True پس از ایجاد حرکات موجودی. از اعمال دوباره جلوگیری می\u200cکند.', verbose_name='موجودی اعمال شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.vendor', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, default='', help_text='اگر خالی باشد از محصول کپی می\u200cشود.', max_length=50, verbose_name='واحد')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قیمت واحد')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.product', verbose_name='محصول')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase', verbose_name='خرید')),
            ],
            options={
                'verbose_name': 'قلم خرید',
                'verbose_name_plural': 'اقلام خرید',
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['vendor'], name='idx_purchase_vendor'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='idx_purchase_status'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date'], name='idx_purchase_date'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase'], name='idx_pi_purchase'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['product'], name='idx_pi_product'),
        ),
    ]
