# Generated by Django 5.2.14 on 2026-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام عمل')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='نرخ پایه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'نوع عمل',
                'verbose_name_plural': 'انواع عمل',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='surgeries_s_code_d4cf1f_idx'), models.Index(fields=['is_active'], name='surgeries_s_is_acti_bddf1f_idx')],
            },
        ),
    ]
