# Generated by Django 5.2.14 on 2026-06-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_seed_job_positions'),
        ('surgeries', '0007_center_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='surgeryhistory',
            name='doctor_or_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_histories', to='employees.employee', verbose_name='پزشک / درمانگر'),
        ),
    ]
