# Generated by Django 5.2.14 on 2026-07-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0013_surgeryhistory_medical_record_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgerytype',
            options={'ordering': ['name'], 'verbose_name': 'نوع عمل جراحی', 'verbose_name_plural': 'انواع عمل جراحی'},
        ),
    ]
