# Generated by Django 5.2.14 on 2026-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0015_surgery_general_info_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='internal_code',
            field=models.CharField(blank=True, help_text='اختیاری — در صورت تکمیل، باید منحصربه\u200cفرد باشد.', max_length=50, null=True, verbose_name='کد داخلی بیمار'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['internal_code'], name='idx_patient_internal_code'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_code__isnull', False), models.Q(('internal_code', ''), _negated=True)), fields=('internal_code',), name='unique_patient_internal_code_when_set', violation_error_message='کد داخلی بیمار باید یکتا باشد.'),
        ),
    ]
