# Generated by Django 5.2.14 on 2026-07-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0018_patient_age_patient_gender'),
        ('surgeries', '0018_second_assistant_surgeon_to_employee'),
    ]

    operations = [
    ]
