# Generated by Django 5.2.14 on 2026-08-19 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0020_patient_marital_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='case_code',
            field=models.CharField(blank=True, help_text='اختیاری — در صورت تکمیل، باید منحصربه\u200cفرد باشد.', max_length=50, null=True, verbose_name='کد پرونده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='شماره موبایل'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('case_code__isnull', False), models.Q(('case_code', ''), _negated=True)), fields=('case_code',), name='unique_patient_case_code_when_set', violation_error_message='کد پرونده باید یکتا باشد.'),
        ),
    ]
