# Generated by Django 5.2.14 on 2026-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(help_text='کد ملی باید منحصربه\u200cفرد باشد.', max_length=20, unique=True, verbose_name='کد ملی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, verbose_name='جنسیت')),
                ('job_position', models.CharField(max_length=200, verbose_name='سمت / عنوان شغلی')),
                ('start_date', models.DateField(verbose_name='تاریخ استخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('personal_phone', models.CharField(max_length=20, verbose_name='تلفن شخصی')),
                ('emergency_contact_phone', models.CharField(help_text='شماره تماس در مواقع اضطراری (مثلاً خانواده).', max_length=20, verbose_name='تلفن اضطراری')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات / یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_emp_is_active'), models.Index(fields=['job_position'], name='idx_emp_job_position'), models.Index(fields=['start_date'], name='idx_emp_start_date'), models.Index(fields=['national_id'], name='idx_emp_national_id')],
            },
        ),
    ]
