# Generated by Django 5.2.14 on 2026-05-26 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام پوزیشن')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'پوزیشن شغلی',
                'verbose_name_plural': 'پوزیشن\u200cهای شغلی',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='idx_emp_job_position',
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobposition', verbose_name='سمت / عنوان شغلی'),
        ),
    ]
